### ISSUE TITLE
Release with jdk8

### ISSUE THREAD

**Issue by pgtoopx** [fslev/jtest-utils#1]
First of all I want to congratulate you on this great job, it really simplifies a lot of work. Today in my company we are working with Java-cucumber framework, and this library would be very useful to us, but we are currently working on JDK 8 and it is not possible to migrate it due to certain dependencies that have not yet been corrected.

I have done some tests locally and I have tested all your code in java version 1.8 and everything works perfectly.

Therefore I would like to propose generating releases in the two versions of java.

Although today I see that the release of versions is not being done automatically, only the tests.

If you are interested I could help automate the releases.

I find this approach correct https://blog.frankel.ch/github-actions-maven-releases/

**Comment by fslev** [comment]
Hi,
I'm glad that you found this library useful. 
Indeed, the project doesn't have automatic release. I've added you as collaborator in order to help with the github actions.
Regarding the Java 8 support you could provide a PR.
P.S. If your are working with Cucumber, you may also find useful the [Cucumber-Jutils](https://github.com/fslev/cucumber-utils) library. Here is a small tutorial: [Cucumber Jutils tutorial](https://github.com/fslev/cucumber-utils-tutorial). Though, they are compiled also with Java 11.
Cheers!

**Comment by fslev** [comment]
For making two different releases for Java 11 and 8, I think you could make use of the 'release' property of the maven compile plugin (as long as the project is built on a platform with java > 9).
Regarding versioning name, I believe the library compiled for Java8 should have .jre8 at the end of its version:
jtest-utils 1.15.jre8

**Comment by pgtoopx** [comment]
Thanks so much, This week I will be working on sending the new version, and I will try to generate the github action to make an automatic deployment.

About your cucumber-utils, I find it very useful, but currently it does not fit with our model, but if I have suggestions for it, I will let you know

**Comment by fslev** [comment]
Meanwhile, I've released version 1.16.jre8 inside Maven Central repository. Should be available witihin two hours.

**Comment by fslev** [comment]
Better yet, I've changed the compiler to use Java 8 by default, as base java version for release.
Thus, we don't have to maintain two separate versions.
Released new version (1.17) to Maven Central repository

**Comment by pgtoopx** [comment]
Great, now you don't need to create separate versions anymore.

**Comment by fslev** [comment]
I will close this issue.
For automatic Maven release, you can create another issue if you want.
If you don't have the time, I can help. Already created necessary configuration for [cucumber-utils](https://github.com/fslev/cucumber-utils)
